CREATE DATABASE IF NOT EXISTS taskmanager;


CREATE TABLE IF NOT EXISTS user(
id_user INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
nome_user VARCHAR(100) NOT NULL,
email_user VARCHAR(200) NOT NULL UNIQUE,
senha_user VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS task(
id_task INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
title_task VARCHAR(45) NOT NULL,
description_task VARCHAR(250),
date_task DATE NOT NULL,
time_task TIME,  
status_task VARCHAR(255) NOT NULL,  
id_user INT NOT NULL REFERENCES user
);

