name: Semantic Release
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Copy .releaserc
        run: cp .github/.releaserc.yml .

      - name: Npm install
        run: npm i -g semantic-release @semantic-release/changelog @semantic-release/git

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: semantic-release